dataSeries = {
            'Vieja':{
                        1:{
                            'headerDat':'Equipo Nro:\t{filename}\t\tCódigo de Cliente: \tID. Subestación:\t        \nNumero de Serie:\tND\tPeriodo:\
                             {periodo} {Utiempo}.\nTensión:     \t{tension} V\t\tFactor de Corrección: {TV}\nCorriente:\t{corriente} Amp\t\t\
                             Factor de Corrección: {TI}\nDia inicio:\t{inicio}\tDia fin:\t{final}\nHora inicio:\t{horaInicio}\tHora fin:\t{horaFinal}\
                             \n\nFecha	Hora\tU\tU Max\tU Min\tTHD1\tFlicker\tAnormalidad\n\t\tV\tV\tV\t%\t%\t\n',
                            'largoRegistro':10,
                            'largoErr':7,
                            'byteSeparador':255,
                            'variables':5,
                            'maxValues':{'V':286,'thd':10,'flicker':2},
                            'formatoReg':'%s\t%0.2f\t%0.2f\t%0.2f\t%0.2f\t%0.3f\t%s\n',
                            'formatoErr':'%s\t%s\n',
                            'getTension':lambda V: V*0.07087628543376923,
                            'getFlicker':lambda x,y,z: ((x*220*.02)/y)*(100/z),
                            'getThd':lambda u,v,w,x,y,z: (100/u)*(abs(v-((w/x)*y)))*18/z,
                            'unpackString':'>HHHHH',
                            'unpackErr':'>BBBBBBB',
                            'unpackHeaderCalibracion':{'string':'HHHHH','indices':[0,1,2,3,4]},
                            'unpackHeader':'>8sx2s2s2s2s2s2s3x2s2s2s2s2sxx',
                            'unpackHeaderSecundario':'>8sx2s2s2s2s2s2s3x2s2s2s2s2sxx',
                            'headerBasura':'',
                            'padding':True,
                            'headerMap':dict([reversed(x) for x in enumerate(['filename','periodo','diaInicio','mesInicio','añoInicio','horaInicio','minInicio','diaFin','mesFin','añoFin','horaFin','minFin'])]),
                            'regIndexes':{'flicker':0,'thd':1,'Vmin':2,'Vmax':3,'V':4},},
                        3:{
                            'headerDat':'Equipo Nro:\t{filename}\t\tCódigo de Cliente: \tID. Subestación:\t        \nNumero de Serie:\t{serie}\tPeriodo:\
                             {periodo} {Utiempo}.\nTensión:     \t{tension} V\t\tFactor de Corrección: {TV}\nCorriente:\t{corriente} Amp\t\t\
                             Factor de Corrección: {TI}\nDia inicio:\t{inicio}\tDia fin:\t{final}\nHora inicio:\t{horaInicio}\tHora fin:\t{horaFinal}\
                             \n\nFecha	Hora\tU\tU Max\tU Min\tTHD1\tFlicker\tAnormalidad\n\t\tV\tV\tV\t%\t%\t\n',
                            'largoRegistro':42,
                            'largoErr':7,
                            'byteSeparador':255,
                            'variables':22,
                            'maxValues':{'V':286,'thd':10,'flicker':2},
                            'formatoReg':'%s\t%0.2f\t%0.2f\t%0.2f\t%0.2f\t%0.3f\t%0.3f\t%0.2f\t%0.2f\t%0.2f\t%0.2f\t%0.3f\t%0.3f\t%0.2f\t%0.2f\t%0.2f\t%0.2f\t%0.3f\t%0.3f\t%0.2f\t%0.3f\t%0.3f\t%0.3f\t%s\n',
                            'formatoErr':'%s\t%s\n',
                            'getTension':lambda V: V*0.008392460165229354,
                            'getCorriente':lambda I: I*0.005086235518683759,
                            'getEnergia':lambda j,k,l: ((((j<<7)|k)<<7)|l)*0.015687283128499985/1000,
                            'getCosPhi':lambda energia,I,V,periodo: energia/(I*V/1000*periodo/60),
                            'unpackString':'>xx x 2x 3b H HHH 2x 3b H HHH 2x 3b H HHH',
                            'unpackErr':'>BBBBBBB',
                            'unpackHeader':'>8s x 2s 2s2s2s2s2s 3x 2s2s2s2s2s 5x 8s 11x',
                            'unpackHeaderSecundario':'>8s x 2s 2s2s2s2s2s 3x 2s2s2s2s2s 3x 8s 12x',
                            'headerBasura':'>14x',
                            'padding':False,
                            'headerMap':dict([reversed(x) for x in enumerate(['serie','periodo','diaInicio','mesInicio','añoInicio','horaInicio','minInicio',
                            'diaFin','mesFin','añoFin','horaFin','minFin','filename'])]),
                            'unpackHeaderCalibracion':{'string':'','indices':None},
                            'regIndexes':{'ETb1':0,'ETb2':1,'ETb3':2,'IT':3,'VTmin':4,'VTmax':5,'VT':6,'ESb1':7,'ESb2':8,'ESb3':9,'IS':10,'VSmin':11,'VSmax':12,'VS':13,'ERb1':14,'ERb2':15,'ERb3':16,'IR':17,'VRmin':18,'VRmax':19,'VR':20,},},
                    },
            '1104':{
                        1:{
                            'headerDat':'Equipo Nro:\t{filename}\t\tCódigo de Cliente: \tID. Subestación:\t        \nNumero de Serie:\tND\tPeriodo:\
                             {periodo} {Utiempo}.\nTensión:     \t{tension} V\t\tFactor de Corrección: {TV}\nCorriente:\t{corriente} Amp\t\t\
                             Factor de Corrección: {TI}\nDia inicio:\t{inicio}\tDia fin:\t{final}\nHora inicio:\t{horaInicio}\tHora fin:\t{horaFinal}\
                             \n\nFecha	Hora\tU\tU Max\tU Min\tTHD1\tFlicker\tAnormalidad\n\t\tV\tV\tV\t%\t%\t\n',
                            'largoRegistro':19,
                            'largoErr':7,
                            'byteSeparador':255,
                            'variables':['V','Vmax','Vmin','thd','flicker'],
                            'maxValues':{'V':286,'Vmax':286,'Vmin':286,'thd':10,'flicker':2},
                            'formatoReg':'%s\t%0.2f\t%0.2f\t%0.2f\t%0.2f\t%0.3f\t%s\n',
                            'formatoErr':'%s\t%s\n',
                            'getTension':lambda x: x*0.1342281848192215,
                            'getFlicker':lambda x,y,z: ((x*220*.02)/y)*(100/z),
                            'getThd':lambda u,v,w,x,y,z: (100/u)*(abs(v-((w/x)*y)))*18/z,
                            'unpackString':'>HH 9x HHH',
                            'unpackErr':'>BBBBBBB',
                            'unpackHeaderCalibracion':{'string':'HxxxxxxxxxxHxxHHxxxxHxx','indices':[3,0,1,4,2]},
                            'unpackHeader':'>8sx2s2s2s2s2s2s3x2s2s2s2s2sxx',
                            'unpackHeaderSecundario':'>8sx2s2s2s2s2s2s3x2s2s2s2s2sxx',
                            'headerBasura':'',
                            'padding':True,
                            'headerMap':dict([reversed(x) for x in enumerate(['filename','periodo','diaInicio','mesInicio','añoInicio','horaInicio','minInicio','diaFin','mesFin','añoFin','horaFin','minFin'])]),
                            'regIndexes':{'flicker':0,'thd':1,'Vmin':2,'Vmax':3,'V':4},},
                        3:{
                            'largoRegistro':54,
                            'largoErr':7,
                            'byteSeparador':255,
                            'factorTension':0.008392393539741385,
                            'factorCorriente':0.0050874767931571524,
                            'factorFlicker':0.0000037580872785202386,
                            'factorThd':0.000490629335175061,
                            'packString':'>HHxxxxxxxxHHHHxxxxxxxxxHHHHxxxxxxxxxHHHH'},
                    },
            '1605':{
                        1:{
                            'headerDat':'Equipo Nro:\t{filename}\t\tCódigo de Cliente: \tID. Subestación:\t        \nNumero de Serie:\tND\tPeriodo:\
                             {periodo} {Utiempo}.\nTensión:     \t{tension} V\t\tFactor de Corrección: {TV}\nCorriente:\t{corriente} Amp\t\t\
                             Factor de Corrección: {TI}\nDia inicio:\t{inicio}\tDia fin:\t{final}\nHora inicio:\t{horaInicio}\tHora fin:\t{horaFinal}\
                             \n\nFecha	Hora\tU\tU Max\tU Min\tTHD U\tFlicker\tAnormalidad\n\t\tV\tV\tV\t%\t%\t\n',
                            'largoRegistro':12,
                            'largoErr':7,
                            'byteSeparador':255,
                            'variables':['V','Vmax','Vmin','thd','flicker'],
                            'maxValues':{'V':286,'Vmax':286,'Vmin':286,'thd':10,'flicker':2},
                            'formatoReg':'%s\t%0.2f\t%0.2f\t%0.2f\t%0.2f\t%0.3f\t%s\n',
                            'formatoErr':'%s\t%s\n',
                            'getTension':lambda x: x*0.00459564208984375,
                            'getFlicker':lambda x:x*4.664380212779652e-09,
                            'getThd':lambda x: x*0.0007659912109375,
                            'unpackString':'IHHHH',
                            'unpackErr':'>BBBBBBB',
                            'unpackHeader':'9x 2s 2s2s2s 2s2s 3x 2s2s2s 2s2s 2x 8s 46x',
                            'unpackHeaderSecundario':'9x 2s 2s2s2s 2s2s 3x 2s2s2s 2s2s 3x 8s 46x',
                            'unpackHeaderCalibracion':{'string':'','indices':None},
                            'headerBasura':'',
                            'padding':False,
                            'headerMap':dict([reversed(x) for x in enumerate(['periodo','diaInicio','mesInicio','añoInicio','horaInicio','minInicio',
                            'diaFin','mesFin','añoFin','horaFin','minFin','filename'])]),
                            'regIndexes':{'flicker':0,'thd':1,'Vmin':2,'Vmax':3,'V':4},},
                        3:{
                            'largoRegistro':54,
                            'largoErr':7,
                            'byteSeparador':255,
                            'factorTension':0.00839227754373019,
                            'factorCorriente':0.005088869461694482,
                            'factorFlicker':0.0,
                            'factorThd':0.0,
                            'packString':'>HHHHHHHHHHxHHHHHHHHxBBBBBBBBHHHH'},},
            '1612':{},}